export type Cluster = 'text' | 'calculators' | 'security' | 'developer' | 'converters' | 'productivity' | 'health';

export interface SEOPageConfig {
  keyword: string;
  slug: string;
  modifier: string;
  cluster: Cluster;
  angle: string;
  themeColor: string;
}

export const SEO_PAGES_CONFIG: SEOPageConfig[] = [
  {
    keyword: 'best text tools online',
    slug: 'best-word-counter-online',
    modifier: 'best online',
    cluster: 'text' as Cluster,
    angle: 'transactional',
    themeColor: '#3b82f6',
  },
  {
    keyword: 'best calculators online',
    slug: 'best-character-counter-online',
    modifier: 'best online',
    cluster: 'text' as Cluster,
    angle: 'transactional',
    themeColor: '#3b82f6',
  },
  {
    keyword: 'best security & random online',
    slug: 'best-case-converter-online',
    modifier: 'best online',
    cluster: 'text' as Cluster,
    angle: 'transactional',
    themeColor: '#3b82f6',
  },
  {
    keyword: 'best developer tools online',
    slug: 'best-remove-extra-spaces-online',
    modifier: 'best online',
    cluster: 'text' as Cluster,
    angle: 'transactional',
    themeColor: '#3b82f6',
  },
  {
    keyword: 'best unit converters online',
    slug: 'best-text-reverser-online',
    modifier: 'best online',
    cluster: 'text' as Cluster,
    angle: 'transactional',
    themeColor: '#3b82f6',
  },
  {
    keyword: 'best productivity online',
    slug: 'best-palindrome-checker-online',
    modifier: 'best online',
    cluster: 'text' as Cluster,
    angle: 'transactional',
    themeColor: '#3b82f6',
  },
  {
    keyword: 'best health & fitness online',
    slug: 'best-json-formatter-online',
    modifier: 'best online',
    cluster: 'text' as Cluster,
    angle: 'transactional',
    themeColor: '#3b82f6',
  },
  {
    keyword: 'best word counter online',
    slug: 'best-lorem-ipsum-generator-online',
    modifier: 'best online',
    cluster: 'text' as Cluster,
    angle: 'transactional',
    themeColor: '#3b82f6',
  },
  {
    keyword: 'best character counter online',
    slug: 'best-text-to-slug-online',
    modifier: 'best online',
    cluster: 'text' as Cluster,
    angle: 'transactional',
    themeColor: '#3b82f6',
  },
  {
    keyword: 'best case converter online',
    slug: 'best-duplicate-line-remover-online',
    modifier: 'best online',
    cluster: 'text' as Cluster,
    angle: 'transactional',
    themeColor: '#3b82f6',
  },
  {
    keyword: 'best remove extra spaces online',
    slug: 'best-binary-converter-online',
    modifier: 'best online',
    cluster: 'text' as Cluster,
    angle: 'transactional',
    themeColor: '#3b82f6',
  },
  {
    keyword: 'best text reverser online',
    slug: 'best-morse-code-converter-online',
    modifier: 'best online',
    cluster: 'text' as Cluster,
    angle: 'transactional',
    themeColor: '#3b82f6',
  },
  {
    keyword: 'best palindrome checker online',
    slug: 'best-list-sorter-online',
    modifier: 'best online',
    cluster: 'text' as Cluster,
    angle: 'transactional',
    themeColor: '#3b82f6',
  },
  {
    keyword: 'best json formatter & validator online',
    slug: 'best-markdown-previewer-online',
    modifier: 'best online',
    cluster: 'text' as Cluster,
    angle: 'transactional',
    themeColor: '#3b82f6',
  },
  {
    keyword: 'best lorem ipsum generator online',
    slug: 'best-text-diff-checker-online',
    modifier: 'best online',
    cluster: 'text' as Cluster,
    angle: 'transactional',
    themeColor: '#3b82f6',
  },
  {
    keyword: 'best text to slug converter online',
    slug: 'best-csv-to-json-online',
    modifier: 'best online',
    cluster: 'text' as Cluster,
    angle: 'transactional',
    themeColor: '#3b82f6',
  },
  {
    keyword: 'best duplicate line remover online',
    slug: 'best-json-to-csv-online',
    modifier: 'best online',
    cluster: 'text' as Cluster,
    angle: 'transactional',
    themeColor: '#3b82f6',
  },
  {
    keyword: 'best binary converter online',
    slug: 'best-yaml-to-json-online',
    modifier: 'best online',
    cluster: 'text' as Cluster,
    angle: 'transactional',
    themeColor: '#3b82f6',
  },
  {
    keyword: 'best morse code converter online',
    slug: 'best-nato-phonetic-online',
    modifier: 'best online',
    cluster: 'text' as Cluster,
    angle: 'transactional',
    themeColor: '#3b82f6',
  },
  {
    keyword: 'best list sorter online',
    slug: 'best-sentiment-analyzer-online',
    modifier: 'best online',
    cluster: 'text' as Cluster,
    angle: 'transactional',
    themeColor: '#3b82f6',
  },
  {
    keyword: 'best markdown previewer online',
    slug: 'best-rot13-encoder-online',
    modifier: 'best online',
    cluster: 'text' as Cluster,
    angle: 'transactional',
    themeColor: '#3b82f6',
  },
  {
    keyword: 'best text diff checker online',
    slug: 'best-zalgo-text-generator-online',
    modifier: 'best online',
    cluster: 'text' as Cluster,
    angle: 'transactional',
    themeColor: '#3b82f6',
  },
  {
    keyword: 'best csv to json converter online',
    slug: 'best-upside-down-text-online',
    modifier: 'best online',
    cluster: 'text' as Cluster,
    angle: 'transactional',
    themeColor: '#3b82f6',
  },
  {
    keyword: 'best json to csv converter online',
    slug: 'best-text-to-speech-online',
    modifier: 'best online',
    cluster: 'text' as Cluster,
    angle: 'transactional',
    themeColor: '#3b82f6',
  },
  {
    keyword: 'best yaml to json converter online',
    slug: 'best-email-extractor-online',
    modifier: 'best online',
    cluster: 'text' as Cluster,
    angle: 'transactional',
    themeColor: '#3b82f6',
  },
  {
    keyword: 'best text to nato phonetic online',
    slug: 'best-basic-calculator-online',
    modifier: 'best online',
    cluster: 'calculators' as Cluster,
    angle: 'transactional',
    themeColor: '#10b981',
  },
  {
    keyword: 'best sentiment analyzer online',
    slug: 'best-percentage-calculator-online',
    modifier: 'best online',
    cluster: 'calculators' as Cluster,
    angle: 'transactional',
    themeColor: '#10b981',
  },
  {
    keyword: 'best rot13 encoder/decoder online',
    slug: 'best-age-calculator-online',
    modifier: 'best online',
    cluster: 'calculators' as Cluster,
    angle: 'transactional',
    themeColor: '#10b981',
  },
  {
    keyword: 'best zalgo text generator online',
    slug: 'best-bmi-calculator-online',
    modifier: 'best online',
    cluster: 'calculators' as Cluster,
    angle: 'transactional',
    themeColor: '#10b981',
  },
  {
    keyword: 'best upside down text online',
    slug: 'best-discount-calculator-online',
    modifier: 'best online',
    cluster: 'calculators' as Cluster,
    angle: 'transactional',
    themeColor: '#10b981',
  },
  {
    keyword: 'best text to speech online',
    slug: 'best-loan-emi-calculator-online',
    modifier: 'best online',
    cluster: 'calculators' as Cluster,
    angle: 'transactional',
    themeColor: '#10b981',
  },
  {
    keyword: 'best email extractor online',
    slug: 'best-scientific-calculator-online',
    modifier: 'best online',
    cluster: 'calculators' as Cluster,
    angle: 'transactional',
    themeColor: '#10b981',
  },
  {
    keyword: 'best basic calculator online',
    slug: 'best-time-duration-calculator-online',
    modifier: 'best online',
    cluster: 'calculators' as Cluster,
    angle: 'transactional',
    themeColor: '#10b981',
  },
  {
    keyword: 'best percentage calculator online',
    slug: 'best-tip-calculator-online',
    modifier: 'best online',
    cluster: 'calculators' as Cluster,
    angle: 'transactional',
    themeColor: '#10b981',
  },
  {
    keyword: 'best age calculator online',
    slug: 'best-compound-interest-calculator-online',
    modifier: 'best online',
    cluster: 'calculators' as Cluster,
    angle: 'transactional',
    themeColor: '#10b981',
  },
  {
    keyword: 'best bmi calculator online',
    slug: 'best-bmr-calculator-online',
    modifier: 'best online',
    cluster: 'calculators' as Cluster,
    angle: 'transactional',
    themeColor: '#10b981',
  },
  {
    keyword: 'best discount calculator online',
    slug: 'best-sales-tax-calculator-online',
    modifier: 'best online',
    cluster: 'calculators' as Cluster,
    angle: 'transactional',
    themeColor: '#10b981',
  },
  {
    keyword: 'best loan emi calculator online',
    slug: 'best-savings-goal-calculator-online',
    modifier: 'best online',
    cluster: 'calculators' as Cluster,
    angle: 'transactional',
    themeColor: '#10b981',
  },
  {
    keyword: 'best scientific calculator online',
    slug: 'best-fuel-cost-calculator-online',
    modifier: 'best online',
    cluster: 'calculators' as Cluster,
    angle: 'transactional',
    themeColor: '#10b981',
  },
  {
    keyword: 'best time duration calculator online',
    slug: 'best-gpa-calculator-online',
    modifier: 'best online',
    cluster: 'calculators' as Cluster,
    angle: 'transactional',
    themeColor: '#10b981',
  },
  {
    keyword: 'best tip calculator online',
    slug: 'best-cgpa-calculator-online',
    modifier: 'best online',
    cluster: 'calculators' as Cluster,
    angle: 'transactional',
    themeColor: '#10b981',
  },
  {
    keyword: 'best compound interest calculator online',
    slug: 'best-auto-loan-calculator-online',
    modifier: 'best online',
    cluster: 'calculators' as Cluster,
    angle: 'transactional',
    themeColor: '#10b981',
  },
  {
    keyword: 'best bmr calculator online',
    slug: 'best-mortgage-payoff-calculator-online',
    modifier: 'best online',
    cluster: 'calculators' as Cluster,
    angle: 'transactional',
    themeColor: '#10b981',
  },
  {
    keyword: 'best sales tax calculator online',
    slug: 'best-unix-timestamp-converter-online',
    modifier: 'best online',
    cluster: 'calculators' as Cluster,
    angle: 'transactional',
    themeColor: '#10b981',
  },
  {
    keyword: 'best savings goal calculator online',
    slug: 'best-base-converter-online',
    modifier: 'best online',
    cluster: 'calculators' as Cluster,
    angle: 'transactional',
    themeColor: '#10b981',
  },
  {
    keyword: 'best fuel cost calculator online',
    slug: 'best-aspect-ratio-calculator-online',
    modifier: 'best online',
    cluster: 'calculators' as Cluster,
    angle: 'transactional',
    themeColor: '#10b981',
  },
  {
    keyword: 'best gpa calculator online',
    slug: 'best-date-difference-calculator-online',
    modifier: 'best online',
    cluster: 'calculators' as Cluster,
    angle: 'transactional',
    themeColor: '#10b981',
  },
  {
    keyword: 'best cgpa calculator online',
    slug: 'best-inflation-calculator-online',
    modifier: 'best online',
    cluster: 'calculators' as Cluster,
    angle: 'transactional',
    themeColor: '#10b981',
  },
  {
    keyword: 'best auto loan calculator online',
    slug: 'best-password-generator-online',
    modifier: 'best online',
    cluster: 'security' as Cluster,
    angle: 'transactional',
    themeColor: '#f43f5e',
  },
  {
    keyword: 'best mortgage payoff calculator online',
    slug: 'best-password-strength-checker-online',
    modifier: 'best online',
    cluster: 'security' as Cluster,
    angle: 'transactional',
    themeColor: '#f43f5e',
  },
  {
    keyword: 'best unix timestamp converter online',
    slug: 'best-random-number-generator-online',
    modifier: 'best online',
    cluster: 'security' as Cluster,
    angle: 'transactional',
    themeColor: '#f43f5e',
  },
  {
    keyword: 'best base converter online',
    slug: 'best-random-name-picker-online',
    modifier: 'best online',
    cluster: 'security' as Cluster,
    angle: 'transactional',
    themeColor: '#f43f5e',
  },
  {
    keyword: 'best aspect ratio calculator online',
    slug: 'best-uuid-generator-online',
    modifier: 'best online',
    cluster: 'security' as Cluster,
    angle: 'transactional',
    themeColor: '#f43f5e',
  },
  {
    keyword: 'best date difference calculator online',
    slug: 'best-qr-code-generator-online',
    modifier: 'best online',
    cluster: 'security' as Cluster,
    angle: 'transactional',
    themeColor: '#f43f5e',
  },
  {
    keyword: 'best inflation calculator online',
    slug: 'best-color-palette-generator-online',
    modifier: 'best online',
    cluster: 'security' as Cluster,
    angle: 'transactional',
    themeColor: '#f43f5e',
  },
  {
    keyword: 'best password generator online',
    slug: 'best-sha256-hash-online',
    modifier: 'best online',
    cluster: 'security' as Cluster,
    angle: 'transactional',
    themeColor: '#f43f5e',
  },
  {
    keyword: 'best password strength online',
    slug: 'best-md5-hash-online',
    modifier: 'best online',
    cluster: 'security' as Cluster,
    angle: 'transactional',
    themeColor: '#f43f5e',
  },
  {
    keyword: 'best random number generator online',
    slug: 'best-coin-flip-dice-online',
    modifier: 'best online',
    cluster: 'security' as Cluster,
    angle: 'transactional',
    themeColor: '#f43f5e',
  },
  {
    keyword: 'best random name picker online',
    slug: 'best-random-string-generator-online',
    modifier: 'best online',
    cluster: 'security' as Cluster,
    angle: 'transactional',
    themeColor: '#f43f5e',
  },
  {
    keyword: 'best uuid generator online',
    slug: 'best-base64-encode-decode-online',
    modifier: 'best online',
    cluster: 'developer' as Cluster,
    angle: 'transactional',
    themeColor: '#8b5cf6',
  },
  {
    keyword: 'best qr code generator online',
    slug: 'best-url-encoder-decoder-online',
    modifier: 'best online',
    cluster: 'developer' as Cluster,
    angle: 'transactional',
    themeColor: '#8b5cf6',
  },
  {
    keyword: 'best color palette generator online',
    slug: 'best-html-minifier-online',
    modifier: 'best online',
    cluster: 'developer' as Cluster,
    angle: 'transactional',
    themeColor: '#8b5cf6',
  },
  {
    keyword: 'best sha-256 hash generator online',
    slug: 'best-css-minifier-online',
    modifier: 'best online',
    cluster: 'developer' as Cluster,
    angle: 'transactional',
    themeColor: '#8b5cf6',
  },
  {
    keyword: 'best md5 hash generator online',
    slug: 'best-js-minifier-online',
    modifier: 'best online',
    cluster: 'developer' as Cluster,
    angle: 'transactional',
    themeColor: '#8b5cf6',
  },
  {
    keyword: 'best coin flip & dice roller online',
    slug: 'best-gradient-generator-online',
    modifier: 'best online',
    cluster: 'developer' as Cluster,
    angle: 'transactional',
    themeColor: '#8b5cf6',
  },
  {
    keyword: 'best random string generator online',
    slug: 'best-box-shadow-generator-online',
    modifier: 'best online',
    cluster: 'developer' as Cluster,
    angle: 'transactional',
    themeColor: '#8b5cf6',
  },
  {
    keyword: 'best base64 encode/decode online',
    slug: 'best-border-radius-generator-online',
    modifier: 'best online',
    cluster: 'developer' as Cluster,
    angle: 'transactional',
    themeColor: '#8b5cf6',
  },
  {
    keyword: 'best url encoder/decoder online',
    slug: 'best-glassmorphism-generator-online',
    modifier: 'best online',
    cluster: 'developer' as Cluster,
    angle: 'transactional',
    themeColor: '#8b5cf6',
  },
  {
    keyword: 'best html minifier online',
    slug: 'best-svg-blob-generator-online',
    modifier: 'best online',
    cluster: 'developer' as Cluster,
    angle: 'transactional',
    themeColor: '#8b5cf6',
  },
  {
    keyword: 'best css minifier online',
    slug: 'best-flexbox-generator-online',
    modifier: 'best online',
    cluster: 'developer' as Cluster,
    angle: 'transactional',
    themeColor: '#8b5cf6',
  },
  {
    keyword: 'best javascript minifier online',
    slug: 'best-grid-generator-online',
    modifier: 'best online',
    cluster: 'developer' as Cluster,
    angle: 'transactional',
    themeColor: '#8b5cf6',
  },
  {
    keyword: 'best gradient generator online',
    slug: 'best-button-generator-online',
    modifier: 'best online',
    cluster: 'developer' as Cluster,
    angle: 'transactional',
    themeColor: '#8b5cf6',
  },
  {
    keyword: 'best box shadow generator online',
    slug: 'best-filter-effects-generator-online',
    modifier: 'best online',
    cluster: 'developer' as Cluster,
    angle: 'transactional',
    themeColor: '#8b5cf6',
  },
  {
    keyword: 'best css border radius generator online',
    slug: 'best-meta-tag-generator-online',
    modifier: 'best online',
    cluster: 'developer' as Cluster,
    angle: 'transactional',
    themeColor: '#8b5cf6',
  },
  {
    keyword: 'best glassmorphism css generator online',
    slug: 'best-json-to-ts-online',
    modifier: 'best online',
    cluster: 'developer' as Cluster,
    angle: 'transactional',
    themeColor: '#8b5cf6',
  },
  {
    keyword: 'best svg blob generator online',
    slug: 'best-contrast-checker-online',
    modifier: 'best online',
    cluster: 'developer' as Cluster,
    angle: 'transactional',
    themeColor: '#8b5cf6',
  },
  {
    keyword: 'best css flexbox generator online',
    slug: 'best-robots-txt-generator-online',
    modifier: 'best online',
    cluster: 'developer' as Cluster,
    angle: 'transactional',
    themeColor: '#8b5cf6',
  },
  {
    keyword: 'best css grid generator online',
    slug: 'best-sitemap-generator-online',
    modifier: 'best online',
    cluster: 'developer' as Cluster,
    angle: 'transactional',
    themeColor: '#8b5cf6',
  },
  {
    keyword: 'best css button generator online',
    slug: 'best-html-table-generator-online',
    modifier: 'best online',
    cluster: 'developer' as Cluster,
    angle: 'transactional',
    themeColor: '#8b5cf6',
  },
  {
    keyword: 'best css filter effects online',
    slug: 'best-image-to-base64-online',
    modifier: 'best online',
    cluster: 'developer' as Cluster,
    angle: 'transactional',
    themeColor: '#8b5cf6',
  },
  {
    keyword: 'best meta tag generator online',
    slug: 'best-base64-to-image-online',
    modifier: 'best online',
    cluster: 'developer' as Cluster,
    angle: 'transactional',
    themeColor: '#8b5cf6',
  },
  {
    keyword: 'best json to typescript online',
    slug: 'best-image-resizer-online',
    modifier: 'best online',
    cluster: 'developer' as Cluster,
    angle: 'transactional',
    themeColor: '#8b5cf6',
  },
];
